from setuptools import setup, find_packages

setup(
    name="credlens",
    version="1.0.0",
    description="AI-powered misinformation detection and education tool",
    author="CredLens Team",
    author_email="info@credlens.ai",
    url="https://github.com/credlens/credlens",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0", 
        "pydantic>=2.5.0",
        "sentence-transformers>=2.2.2",
        "transformers>=4.35.2",
        "torch>=2.1.0",
        "faiss-cpu>=1.7.4",
        "requests>=2.31.0",
        "beautifulsoup4>=4.12.2",
        "sqlite-utils>=3.35.2",
        "python-multipart>=0.0.6",
        "aiofiles>=23.2.0",
        "numpy>=1.24.3",
        "scikit-learn>=1.3.0",
        "nltk>=3.8.1",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Education",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Education",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    keywords="misinformation, fact-checking, ai, education, media-literacy, nlp",
    project_urls={
        "Bug Reports": "https://github.com/credlens/credlens/issues",
        "Source": "https://github.com/credlens/credlens",
        "Documentation": "https://credlens.readthedocs.io/",
    },
)